version: 2.1

jobs:
  test:
    docker:
      - image: twitchautomation/salesforce-cx-repo:latest
    steps:
      - checkout
      - run:
          name: install packages
          command: npm install
      - run:
          name: Run Test
          command: yarn run test-remote
      - run:
          name: generate allure report
          command: |
            npm install -g allure-commandline
            allure generate --clean
          when: always
      - store_artifacts:
          path: /home/circleci/project/allure-report
     
workflows:
  orb-free-workflow:
    jobs:
      - test
