version: 2.1

jobs:
  test:
    docker:
      - image: twitchautomation/salesforce-cx-repo:latest
    steps:
      - checkout
          
      - run:
          name: install packages
          command: npm install
          
      - run:
          name: Run Test
          command: yarn run test-remote
          
      - run:
          name: generate allure report
          command: |
            sudo npm install -g allure-commandline
            echo BRANCH=development >> allure-results/environment.properties
            echo COMMIT=$CI_PULL_REQUEST/commits/$CIRCLE_SHA1 >> allure-results/environment.properties
            allure generate --clean && allure open
          when: always
          
     - store_artifacts:
          path: /home/circleci/project/allure-report
     
workflows:
  orb-free-workflow:
    jobs:
      - test
