version: 2.1

jobs:
  test:
    docker:
      - image: ianwalter/puppeteer:latest
    steps:
      - run:
          name: install packages
          command: npm install
      - run:
          name: Run Test
          command: yarn run test-remote
workflows:
  orb-free-workflow:
    jobs:
      - test