version: 2.1

jobs:
  test:
    docker:
      - image: ianwalter/puppeteer:latest
    steps:
      - checkout

      - run:
          name: install packages
          command: npm install

      - run:
          name: Run Test
          command: yarn run test-remote --spec mySuite1.js --spec mySuite2.js

workflows:
  orb-free-workflow:
    jobs:
      - test
