version: 2.1

jobs:
  test:
    docker:
      - image: twitchautomation/salesforce-cx-repo:latest
    steps:
      - checkout
          
      - run:
          name: install packages
          command: npm install
          
      - run:
          name: Run Test
          command: yarn run test-remote
     
workflows:
  orb-free-workflow:
    jobs:
      - test
