version: 2.1

jobs:
  test:
    docker:
      - image: ianwalter/puppeteer:latest
    steps:
      - checkout
      
      - run:
          name: install packages
          command: npm i
     
      - run: mkdir ~/junit
      - run:
          command: mocha test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

workflows:
  orb-free-workflow:
    jobs:
      - test
